### ISSUE TITLE
<节点名称> 申请成为主网记账节点

### ISSUE THREAD

**Issue by JaszOnly** [newtonproject/newchain-nodes#2]
#### 节点基本信息

- 对外显示名称：<LEDGER-NewAmbassador>
- 矿工地址：<0x8a4bbc3599a119Ad8c9C45e43521dbF1e803dC85>
- RPC Url（可以是服务器地址加端口）： <51.79.167.42:8801>
- NewPay社群节点中展示机器节点主体（个人、社群、组织）名称：<LEDGER-NewAmbassador>
- 节点负责人及联系方式（手机、邮箱、微信、telegram等均可）： <Jasz, wechat：jasz929>
- 用于接收主网矿工纪念币的主网NEW地址(NewPay或NewMask)： <NEW182ZheiEbSBW3SbtETmXEgdG5X9GvFuLRun2>

#### Newton生态

<在这里简单介绍您的节点，成立时间，社群活跃度，社群加入方式等等。>

<这里描述您的节点能够为牛顿生态提供哪些帮助？>

**Comment by VieYang** [comment]
Done
