### ISSUE TITLE
重置NewChain测试网

### ISSUE THREAD

**Issue by VieYang** [newtonproject/newchain-nodes#4]
现行NewChain测试网自2018年12月20日运行至今，支撑着Newton生态各个应用的测试。
截止2月23日，测试网相关数据如下：

- 总区块数： 22,830,500
- 总地址数： 7,685
- 总交易笔数： 238,937,124
- 总的机器节点数量： 25
- 节点数据大小： 121G

NewChain测试网交易笔数是以太坊Ropsten测试网的2倍，是以太坊Rinkeby测试网的3倍。
但这引发其节点占用存储过大，数据处理过慢，同时也使得测试网节点运行者成本过大。
因此建议重置测试网。

**Comment by gjw00001** [comment]
支持重置测试网

**Comment by VieYang** [comment]
## 测试网机器
- 参加机器节点的用户可以获得1亿测试网NEW空投
- 参加机器节点的用户需要在测试网NewPay中创建社群节点，并且锁仓至少一千万的NEW
- 机器节点需要不定期审核新的测试网节点并审批
- 社群中对测试网的需求均有机器节点提供，由各自节点决定有偿或无偿
- 机器节点可以挖矿，矿量约站每天释放量的20%，具体可以参考[NEP-40](https://neps.newtonproject.org/neps/nep-40/)

**Comment by VieYang** [comment]
## 节点重置后会发生什么？
- 现有机器节点数据、浏览器、NewPay节点、交易记录等均被清空
- 所有账户余额清零
- 所有现有Token被清除，需要重新发token

## 机器节点需要做什么？
- 申请节点（优先考虑之前运行的测试网节点）
- 运行如下命令清楚现有节点
```
cd ~ && mkdir -p newton && cd newton && cp /data/newchain/testnet/nodedata/geth/nodekey . && sudo supervisorctl stop newchain newchainguard && rm -r /data/newchain/testnet/nodedata/geth/ && mkdir -p /data/newchain/testnet/nodedata/geth/ && cp nodekey /data/newchain/testnet/nodedata/geth/nodekey
```

运行如下命令部署新节点：
```
curl -L https://release.cloud.diynova.com/newton/newchain-deploy/testnet/newchain.sh | sudo bash
```

## 普通用户需要做什么？
- NewPay
    - 备份现有钱包的助记词
    - 删除现有钱包
    - 导入助记词或新建钱包
    - 注册NewID
    - 找社群节点负责人领取测试网NEW
- NewMask
   - 余额归零，需要找节点负责人领取测试网NEW

**Comment by VieYang** [comment]
## 机器节点挖矿
- 重置测试网后，上线机器节点挖矿
- 机器节点按照NewPay对应节点的锁仓量均分20%矿量

**Comment by VieYang** [comment]
## 机器节点需要做什么？
- 需要所有现有测试网节点配合执行
- 运行如下命令清空现有节点数据
```
cd ~ && mkdir -p newton && cd newton && cp /data/newchain/testnet/nodedata/geth/nodekey . && sudo supervisorctl stop newchain newchainguard && rm -r /data/newchain/testnet/nodedata/geth/ && mkdir -p /data/newchain/testnet/nodedata/geth/ && cp nodekey /data/newchain/testnet/nodedata/geth/nodekey
```

运行如下命令部署新节点：
```
curl -L https://release.cloud.diynova.com/newton/newchain-deploy/testnet/newchain.sh | sudo bash
```

同步完成后，运行如下命令成为记账节点：

```
cd /data/newchain/mainnet/ && curl -L https://release.cloud.diynova.com/newton/newchain-deploy/mainnet/newchain-mine.sh -o newchain-mine.sh && chmod +x newchain-mine.sh && ./newchain-mine.sh
```

该命令会下载并运行 newchain-mine.sh 脚本，会创建沿用之前的矿工地址，并启用挖矿。

等待其它已加入的记账节点批准。

**Comment by VieYang** [comment]
## 普通用户需要做什么？
- NewPay
    - 备份现有钱包的助记词
    - 删除现有钱包
    - 导入助记词或新建钱包
    - 注册NewID
    - 找机器节点负责人领取测试网NEW
- NewMask
   - 余额归零，需要找机器节点负责人领取测试网NEW

**Comment by VieYang** [comment]
## 节点硬分叉区块高度

```
"homesteadBlock": 1
"eip150Block": 2
"eip155Block": 3
"eip158Block": 3
"byzantiumBlock": 4
"constantinopleBlock": 10
"petersburgBlock": 10
"istanbulBlock": 10
```

具体参考： https://github.com/newtonproject/newchain-deploy/blob/6b347598094310abc013cfbe3f9aad6741c6e1cb/testnet/share/newchaintestnet.json#L4

**Comment by VieYang** [comment]
已完成升级的节点：

|升级状态|序号 |名称 | 矿工地址  | RPC Url |
|--|--|--|--|--|
|| 1 |Aussie Node | 0xc66760726cD32DeC091D47646552351444e740EC | http://139.99.155.31:8801
||2|联创动力 | 0xBf35d73f70Ea8c74aD0F58c8800CBdE52462536b | http://111.229.219.19:8801
||3|JiXiaNewton (稷下) | 0x25220Fb69c5daDd43117b7DFFd47aDB551855ca9 | http://207.148.24.237:8801
||4|lite moment | 0x12b0C1BcCf7601557650F73dF539aa80D3A80105 | http://miner.litemoment.com:8801
||5|火牛 | 0x17FC9cA7aF608D2A5e186549298bB2Ed79c2578F | http://106.14.58.1:8801
||6|News牛使 | 0xC81bC73e65E81924eb4D65C6b975D49112595eE9 | http://51.79.156.75:8801
||7|NewAmbassador | 0x1b1Cd94d13d7D185990fA06C11FD088ab9b15f7D | http://139.99.61.166:8801
||8|Mars | 0xa3203F8Ad655AA6c8921721087FC576489A00Bf0 | http://139.196.58.165:8801
||9|梦想社区 IMX | 0xeDC52506b7d2cB9db499Bd89929763b5F311b7E6 | http://47.108.81.110:8801
||10|NewWorld | 0x7B05ec771D3Bb7233C6C08A0AACE352Eb65F5339 | http://106.55.254.136:8801
||11|CyberG | 0x18A9a91Ce471E04F92Cf105a186d00a788737c48 | http://112.126.61.216:8801
||12|Loading | 0xb5502488609427fe815aaff997610254acC72755 | http://101.37.64.152:8801
||13|JiXiaNewton2 | 0xe8ce5308ac02d5143b37535e30c1b3797dcca83d | http://107.182.187.108:8801
||14|Rain | 0x6C741f0e1a677f317198Fb14B48bC2F80fA72Fe1 | http://8.129.22.238:8801
||15|群山投资 | 0xa25fED0Eb1F221C231D05321cfb0e9F7636ecE84 | http://47.115.137.55:8801
||16|瞄财数字 | 0x77bd3e4bf5db39e2d98ca62f31a67cdd412c1173 | http://182.92.117.172:8801
||17|JiXiaNewton3 | 0xE3CD676D11bBB7b4518821d48Fca18cDB88aFe91 | http://119.145.38.77:8801
|√|18|共赢社区 | 0x1c6119C4f7b49B7D24088Ed57D04fef50bd162Ca | http://39.98.182.29:8801
||19|菩提树下 | 0x92316ba0b80a2eafb9d16e2d2b96348b5ae5411f | http://39.98.254.225:8801
||20|TXNewton | 0x1464eb2022a4c68643748edc26d1254a61f08911 | http://113.105.67.90:8801
||21|忙着幸福|  0x99f65184f1DC8373B2A658EA477AAc57474eC21D  | http://8.134.8.152:8801
||22|NewPai | 0xf0a1a291e4deefa1d06a475250023d7a9a7b10a7 | http://39.98.91.255:8801
||23|DAPP | 0xc5c4f49882c6da25cefb192703737345e1230e79 | http://113.105.67.91:8801
|√|24|X Team | 0x1d7e06ad19339263a51ee47e11b4ffd10d4a83ba | https://rpc1.newchain.newtonproject.org
