### ISSUE TITLE
evan3345 申请成为测试网记账节点

### ISSUE THREAD

**Issue by evanliuchina** [newtonproject/newchain-nodes#7]
#### 节点基本信息

- 对外显示名称：evan3345
- 矿工地址：0xede435d5d6b6e1ae299d8cb706b83e3d27590d4a
- RPC Url（可以是服务器地址加端口）： http://20.89.90.151:8801
- NewPay社群节点中展示机器节点主体（个人、社群、组织）名称：evan3345
- 节点负责人及联系方式（手机、邮箱、微信、telegram等均可）： evanliuchina@gmail.com
- 用于接收主网矿工纪念币的主网NEW地址(NewPay或NewMask)： NEW182TmsV7pLYGksug7zCcNkjmUA2hDDVdEYxj

#### Newton生态

个人节点

**Comment by evan3345** [comment]
/data/newchain/testnet/bin/geth attach /data/newchain/testnet/nodedata/geth.ipc --exec 'clique.propose("0xede435d5d6b6e1ae299d8cb706b83e3d27590d4a", true)'

**Comment by xiawu** [comment]
Thanks for your apply. Audit is in the process.

**Comment by QlDoors** [comment]
您好，这边检测到您的节点已经停机，如果您还想加入牛顿测试网，请恢复您的节点
