### ISSUE TITLE
<mars> 申请成为测试网记账节点

### ISSUE THREAD

**Issue by gjw00001** [newtonproject/newchain-nodes#8]
#### 节点基本信息

- 对外显示名称：mars
- 矿工地址：0xF9Fb48285e760dC4fC745150fF7dFf278d966b89
- RPC Url（可以是服务器地址加端口）： http://139.196.58.165:8801
- NewPay社群节点中展示机器节点主体（个人、社群、组织）名称：mars
- 节点负责人及联系方式（手机、邮箱、微信、telegram等均可）： gjw00001@126.com
- 用于接收主网矿工纪念币的主网NEW地址(NewPay或NewMask)： NEW182KWmSyNtMbXkKRGpyK7t5iHStkVxSpTaBf

#### Newton生态

自牛顿成立开始，一直不离不弃，始终坚信牛顿一定能在区块链中做出成绩。加油，牛顿

**Comment by QlDoors** [comment]
节点已经添加成功，您可以通过下面命令检测  

```
/data/newchain/testnet/bin/geth attach /data/newchain/testnet/nodedata/geth.ipc --exec 'clique.getSigners()'
```
